//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> RemainderDate { get; set; }
        public Nullable<int> EstimatedCost { get; set; }
        public string Description { get; set; }
    }
}
